In [114]:
import pandas as pd
import pickle

from sqlalchemy import create_engine
import sys
import pymysql

# Library Imports.
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Allows plots to appear directly in the notebook.
%matplotlib inline

from patsy import dmatrices
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [116]:
db_connection = "mysql+pymysql://{0}:{1}@{2}/{3}".format(user, password, host, dbname)
engine = create_engine(db_connection)

In [118]:
query_string = pd.read_sql_query(
"""SELECT number, real_date AS Date, 
real_time as Time, available_bikes,
DAYOFWEEK(real_date) AS Day, 
EXTRACT(HOUR FROM real_time) as Hour, 
MONTH(real_date) AS Month 
FROM DublinBikes.dynamic 
WHERE real_date <= '2020-03-20'""", engine)


df_bikes = pd.DataFrame(query_string).drop_duplicates()

df_bikes

        number        Date      Time  available_bikes  Day  Hour  Month
0           42  2020-02-27  16:53:19               14    5    16      2
1           30  2020-02-27  16:52:26                2    5    16      2
2           54  2020-02-27  16:51:43                8    5    16      2
3          108  2020-02-27  16:47:10                4    5    16      2
4           56  2020-02-27  16:53:25               15    5    16      2
...        ...         ...       ...              ...  ...   ...    ...
664254      38  2020-03-20  23:59:27               26    6    23      3
664266      25  2020-03-20  23:59:31                2    6    23      3
664276      75  2020-03-20  23:59:14               16    6    23      3
664287      57  2020-03-20  23:59:28                6    6    23      3
664292     103  2020-03-20  23:59:33               14    6    23      3

[393511 rows x 7 columns]

In [119]:
query_string_w = pd.read_sql_query(
"""SELECT Main, Year, Month,
Temp, Day,
EXTRACT(HOUR FROM True_Time) AS Hour
FROM DublinBikes.testWeather 
GROUP BY Year, Month, Day, Hour
""", engine)

df_weather = pd.DataFrame(query_string_w)
df_weather

        Main  Year Month   Temp Day  Hour
0       Rain  2020     2   8.97  19    12
1       Rain  2020     2   8.97  19    13
2       Rain  2020     2   9.82  19    17
3       Rain  2020     2   9.65  19    21
4       Rain  2020     2   4.43  20    10
...      ...   ...   ...    ...  ..   ...
1140  Clouds  2020     4  14.94   8    18
1141  Clouds  2020     4     13   8    19
1142  Clouds  2020     4   9.57   8    20
1143  Clouds  2020     4   8.93   8    21
1144  Clouds  2020     4   7.96   8    22

[1145 rows x 6 columns]

In [120]:
df_weather.dtypes

Main     object
Year     object
Month    object
Temp     object
Day      object
Hour      int64
dtype: object

In [121]:
cols = ['Year', 'Month', 'Day', 'Hour'] 
for col in cols:
    df_weather[col] = df_weather[col].astype('int64')
df_weather.dtypes

Main     object
Year      int64
Month     int64
Temp     object
Day       int64
Hour      int64
dtype: object

In [122]:
df_weather['Temp'] = df_weather['Temp'].astype('float64')
df_weather['Main'] = df_weather['Main'].astype('category')
df_weather.dtypes

Main     category
Year        int64
Month       int64
Temp      float64
Day         int64
Hour        int64
dtype: object

In [123]:
df_joined = pd.merge(df_bikes, df_weather, how="inner", on=['Month', 'Day', 'Hour'])
df_joined

,number,Date,Time,available_bikes,Day,Hour,Month,Main,Year,Temp
0,42,2020-03-01,00:03:20,29,1,0,3,Clouds,2020,3.51
1,54,2020-03-01,00:01:43,8,1,0,3,Clouds,2020,3.51
2,48,2020-03-01,00:00:00,26,1,0,3,Clouds,2020,3.51
3,13,2020-03-01,00:03:39,1,1,0,3,Clouds,2020,3.51
4,81,2020-03-01,00:01:19,22,1,0,3,Clouds,2020,3.51
...,...,...,...,...,...,...,...,...,...,...
363406,3,2020-03-14,23:57:57,12,7,23,3,Rain,2020,10.39
363407,29,2020-03-14,23:56:19,28,7,23,3,Rain,2020,10.39
363408,103,2020-03-14,23:59:31,7,7,23,3,Rain,2020,10.39
363409,28,2020-03-14,23:58:39,10,7,23,3,Rain,2020,10.39
363410,21,2020-03-14,23:57:03,10,7,23,3,Rain,2020,10.39

In [124]:
df_joined.drop(['Date', 'Time', 'Year', 'Month'], axis=1, inplace=True)

In [125]:
df_joined['Main'].unique()

[Clouds, Rain, Clear, Fog, Drizzle]
Categories (5, object): [Clouds, Rain, Clear, Fog, Drizzle]

In [126]:
df_joined

        number  available_bikes  Day  Hour    Main   Temp
0           42               29    1     0  Clouds   3.51
1           54                8    1     0  Clouds   3.51
2           48               26    1     0  Clouds   3.51
3           13                1    1     0  Clouds   3.51
4           81               22    1     0  Clouds   3.51
...        ...              ...  ...   ...     ...    ...
363406       3               12    7    23    Rain  10.39
363407      29               28    7    23    Rain  10.39
363408     103                7    7    23    Rain  10.39
363409      28               10    7    23    Rain  10.39
363410      21               10    7    23    Rain  10.39

[363411 rows x 6 columns]

In [128]:
df_joined.reset_index(drop=True, inplace=True)

In [129]:
df_joined.sort_values(by=['number', 'Day', 'Hour'])

        number  available_bikes  Day  Hour    Main   Temp
41           2                2    1     0  Clouds   3.51
156          2                2    1     0  Clouds   3.51
270          2                2    1     0  Clouds   3.51
436          2                2    1     0  Clouds   3.51
548          2                2    1     0  Clouds   3.51
...        ...              ...  ...   ...     ...    ...
362867     117                6    7    23    Rain  10.39
362980     117                6    7    23    Rain  10.39
363096     117                6    7    23    Rain  10.39
363211     117                6    7    23    Rain  10.39
363331     117                6    7    23    Rain  10.39

[363411 rows x 6 columns]

In [130]:
df_joined_dummies = df_joined.copy()
df_joined_dummies = pd.get_dummies(df_joined_dummies)

df_joined_dummies.dtypes

number               int64
available_bikes      int64
Day                  int64
Hour                 int64
Temp               float64
Main_Clear           uint8
Main_Clouds          uint8
Main_Drizzle         uint8
Main_Fog             uint8
Main_Mist            uint8
Main_Rain            uint8
dtype: object

In [131]:
df_joined_dummies["Main_Mist"].fillna(0, inplace = True)

In [132]:
df_joined_dummies

,number,available_bikes,Day,Hour,Temp,Main_Clear,Main_Clouds,Main_Drizzle,Main_Fog,Main_Mist,Main_Rain
0,42,29,1,0,3.51,0,1,0,0,0,0
1,54,8,1,0,3.51,0,1,0,0,0,0
2,48,26,1,0,3.51,0,1,0,0,0,0
3,13,1,1,0,3.51,0,1,0,0,0,0
4,81,22,1,0,3.51,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
363406,3,12,7,23,10.39,0,0,0,0,0,1
363407,29,28,7,23,10.39,0,0,0,0,0,1
363408,103,7,7,23,10.39,0,0,0,0,0,1
363409,28,10,7,23,10.39,0,0,0,0,0,1
363410,21,10,7,23,10.39,0,0,0,0,0,1

In [133]:
station_dfs = [] 
for i in range(2, 118):
    station_dfs.append(df_joined_dummies[df_joined_dummies['number'] == i])
station_dfs

[        number  available_bikes  Day  Hour   Temp  Main_Clear  Main_Clouds  \
 41           2                2    1     0   3.51           0            1
 156          2                2    1     0   3.51           0            1
 270          2                2    1     0   3.51           0            1
 436          2                2    1     0   3.51           0            1
 548          2                2    1     0   3.51           0            1
 ...        ...              ...  ...   ...    ...         ...          ...
 362930       2                7    7    23  10.39           0            0
 363043       2                7    7    23  10.39           0            0
 363161       2                7    7    23  10.39           0            0
 363277       2                7    7    23  10.39           0            0
 363391       2                7    7    23  10.39           0            0

         Main_Drizzle  Main_Fog  Main_Mist  Main_Rain
 41                 0         0          0          0
 156                0         0          0          0
 270                0         0          0          0
 436                0         0          0          0
 548                0         0          0          0
 ...              ...       ...        ...        ...
 362930             0         0          0          1
 363043             0         0          0          1
 363161             0         0          0          1
 363277             0         0          0          1
 363391             0         0          0          1

 [3123 rows x 11 columns],
         number  available_bikes  Day  Hour   Temp  Main_Clear  Main_Clouds  \
 113          3               14    1     0   3.51           0            1
 229          3               14    1     0   3.51           0            1
 350          3               14    1     0   3.51           0            1
 456          3               14    1     0   3.51           0            1
 567          3               14    1     0   3.51           0            1
 ...        ...              ...  ...   ...    ...         ...          ...
 362945       3               11    7    23  10.39           0            0
 363056       3               11    7    23  10.39           0            0
 363174       3               12    7    23  10.39           0            0
 363291       3               12    7    23  10.39           0            0
 363406       3               12    7    23  10.39           0            0

         Main_Drizzle  Main_Fog  Main_Mist  Main_Rain
 113                0         0          0          0
 229                0         0          0          0
 350                0         0          0          0
 456                0         0          0          0
 567                0         0          0          0
 ...              ...       ...        ...        ...
 362945             0         0          0          1
 363056             0         0          0          1
 363174             0         0          0          1
 363291             0         0          0          1
 363406             0         0          0          1

 [3356 rows x 11 columns],
         number  available_bikes  Day  Hour   Temp  Main_Clear  Main_Clouds  \
 21           4               20    1     0   3.51           0            1
 137          4               20    1     0   3.51           0            1
 251          4               20    1     0   3.51           0            1
 398          4               20    1     0   3.51           0            1
 512          4               20    1     0   3.51           0            1
 ...        ...              ...  ...   ...    ...         ...          ...
 362860       4                2    7    23  10.39           0            0
 362972       4                2    7    23  10.39           0            0
 363086       4                2    7    23  10.39           0            0
 363203       4                2    7    23  10.39           0            0
 363322       4                2    7    23  10.39           0            0

         Main_Drizzle  Main_Fog  Main_Mist  Main_Rain
 21                 0         0          0          0
 137                0         0          0          0
 251                0         0          0          0
 398                0         0          0          0
 512                0         0          0          0
 ...              ...       ...        ...        ...
 362860             0         0          0          1
 362972             0         0          0          1
 363086             0         0          0          1
 363203             0         0          0          1
 363322             0         0          0          1

 [3213 rows x 11 columns],
         number  available_bikes  Day  Hour   Temp  Main_Clear  Main_Clouds  \
 83           5               12    1     0   3.51           0            1
 133          5               13    1     0   3.51           0            1
 199          5               12    1     0   3.51           0            1
 319          5               12    1     0   3.51           0            1
 393          5               12    1     0   3.51           0            1
 ...        ...              ...  ...   ...    ...         ...          ...
 362970       5               10    7    23  10.39           0            0
 363082       5               10    7    23  10.39           0            0
 363139       5               10    7    23  10.39           0            0
 363255       5                9    7    23  10.39           0            0
 363370       5                9    7    23  10.39           0            0

         Main_Drizzle  Main_Fog  Main_Mist  Main_Rain
 83                 0         0          0          0
 133                0         0          0          0
 199                0         0          0          0
 319                0         0          0          0
 393                0         0          0          0
 ...              ...       ...        ...        ...
 362970             0         0          0          1
 363082             0         0          0          1
 363139             0         0          0          1
 363255             0         0          0          1
 363370             0         0          0          1

 [3845 rows x 11 columns],
         number  available_bikes  Day  Hour   Temp  Main_Clear  Main_Clouds  \
 66           6               20    1     0   3.51           0            1
 179          6               20    1     0   3.51           0            1
 298          6               20    1     0   3.51           0            1
 361          6               20    1     0   3.51           0            1
 476          6               20    1     0   3.51           0            1
 ...        ...              ...  ...   ...    ...         ...          ...
 362840       6               17    7    23  10.39           0            0
 362954       6               17    7    23  10.39           0            0
 363065       6               17    7    23  10.39           0            0
 363183       6               17    7    23  10.39           0            0
 363300       6               17    7    23  10.39           0            0

         Main_Drizzle  Main_Fog  Main_Mist  Main_Rain
 66                 0         0          0          0
 179                0         0          0          0
 298                0         0          0          0
 361                0         0          0          0
 476                0         0          0          0
 ...              ...       ...        ...        ...
 362840             0         0          0          1
 362954             0         0          0          1
 363065             0         0          0          1
 363183             0         0          0          1
 363300             0         0          0          1

 [3266 rows x 11 columns],
         number  available_bikes  Day  Hour   Temp  Main_Clear  Main_Clouds  \
 22           7                7    1     0   3.51           0            1
 139          7                7    1     0   3.51           0            1
 253          7                7    1     0   3.51           0            1
 401          7                7    1     0   3.51           0            1
 515          7                7    1     0   3.51           0            1
 ...        ...              ...  ...   ...    ...         ...          ...
 362913       7                9    7    23  10.39           0            0
 363026       7                9    7    23  10.39           0            0
 363089       7                8    7    23  10.39           0            0
 363205       7                7    7    23  10.39           0            0
 363324       7                7    7    23  10.39           0            0

         Main_Drizzle  Main_Fog  Main_Mist  Main_Rain
 22                 0         0          0          0
 139                0         0          0          0
 253                0         0          0          0
 401                0         0          0          0
 515                0         0          0          0
 ...              ...       ...        ...        ...
 362913             0         0          0          1
 363026             0         0          0          1
 363089             0         0          0          1
 363205             0         0          0          1
 363324             0         0          0          1

 [3085 rows x 11 columns],
         number  available_bikes  Day  Hour   Temp  Main_Clear  Main_Clouds  \
 92           8                1    1     0   3.51           0            1
 208          8                1    1     0   3.51           0            1
 327          8                0    1     0   3.51           0            1
 412          8                0    1     0   3.51           0            1
 526          8                0    1     0   3.51           0            1
 ...        ...              ...  ...   ...    ...         ...          ...
 362868       8                3    7    23  10.39           0            0
 362981       8                2    7    23  10.39           0            0
 363097       8                2    7    23  10.39           0            0
 363212       8                2    7    23  10.39           0            0
 363332       8                2    7    23  10.39           0            0

         Main_Drizzle  Main_Fog  Main_Mist  Main_Rain
 92                 0         0          0          0
 208                0         0          0          0
 327                0         0          0          0
 412                0         0          0          0
 526                0         0          0          0
 ...              ...       ...        ...        ...
 362868             0         0          0          1
 362981             0         0          0          1
 363097             0         0          0          1
 363212             0         0          0          1
 363332             0         0          0          1

 [3674 rows x 11 columns],
         number  available_bikes  Day  Hour   Temp  Main_Clear  Main_Clouds  \
 16           9               13    1     0   3.51           0            1
 131          9               13    1     0   3.51           0            1
 195          9               12    1     0   3.51           0            1
 316          9               12    1     0   3.51           0            1
 388          9               11    1     0   3.51           0            1
 ...        ...              ...  ...   ...    ...         ...          ...
 362855       9                0    7    23  10.39           0            0
 362967       9                0    7    23  10.39           0            0
 363079       9                0    7    23  10.39           0            0
 363197       9                0    7    23  10.39           0            0
 363316       9                0    7    23  10.39           0            0

         Main_Drizzle  Main_Fog  Main_Mist  Main_Rain
 16                 0         0          0          0
 131                0         0          0          0
 195                0         0          0          0
 316                0         0          0          0
 388                0         0          0          0
 ...              ...       ...        ...        ...
 362855             0         0          0          1
 362967             0         0          0          1
 363079             0         0          0          1
 363197             0         0          0          1
 363316             0         0          0          1

 [3930 rows x 11 columns],
         number  available_bikes  Day  Hour   Temp  Main_Clear  Main_Clouds  \
 47          10               16    1     0   3.51           0            1
 161         10               16    1     0   3.51           0            1
 275         10               15    1     0   3.51           0            1
 443         10               15    1     0   3.51           0            1
 555         10               15    1     0   3.51           0            1
 ...        ...              ...  ...   ...    ...         ...          ...
 362935      10               11    7    23  10.39           0            0
 363046      10               10    7    23  10.39           0            0
 363164      10               10    7    23  10.39           0            0
 363280      10               11    7    23  10.39           0            0
 363346      10                9    7    23  10.39           0            0

         Main_Drizzle  Main_Fog  Main_Mist  Main_Rain
 47                 0         0          0          0
 161                0         0          0          0
 275                0         0          0          0
 443                0         0          0          0
 555                0         0          0          0
 ...              ...       ...        ...        ...
 362935             0         0          0          1
 363046             0         0          0          1
 363164             0         0          0          1
 363280             0         0          0          1
 363346             0         0          0          1

 [3657 rows x 11 columns],
         number  available_bikes  Day  Hour   Temp  Main_Clear  Main_Clouds  \
 9           11                0    1     0   3.51           0            1
 125         11                0    1     0   3.51           0            1
 241         11                0    1     0   3.51           0            1
 379         11                0    1     0   3.51           0            1
 494         11                0    1     0   3.51           0            1
 ...        ...              ...  ...   ...    ...         ...          ...
 362849      11                2    7    23  10.39           0            0
 363017      11                2    7    23  10.39           0            0
 363133      11                2    7    23  10.39           0            0
 363250      11                2    7    23  10.39           0            0
 363366      11                2    7    23  10.39           0            0

         Main_Drizzle  Main_Fog  Main_Mist  Main_Rain
 9                  0         0          0          0
 125                0         0          0          0
 241                0         0          0          0
 379                0         0          0          0
 494                0         0          0          0
 ...              ...       ...        ...        ...
 362849             0         0          0          1
 363017             0         0          0          1
 363133             0         0          0          1
 363250             0         0          0          1
 363366             0         0          0          1

 [3081 rows x 11 columns],
         number  available_bikes  Day  Hour   Temp  Main_Clear  Main_Clouds  \
 105         12                1    1     0   3.51           0            1
 220         12                1    1     0   3.51           0            1
 341         12                1    1     0   3.51           0            1
 433         12                1    1     0   3.51           0            1
 545         12                1    1     0   3.51           0            1
 ...        ...              ...  ...   ...    ...         ...          ...
 362928      12                5    7    23  10.39           0            0
 363041      12                6    7    23  10.39           0            0
 363159      12                6    7    23  10.39           0            0
 363274      12                6    7    23  10.39           0            0
 363389      12                6    7    23  10.39           0            0

         Main_Drizzle  Main_Fog  Main_Mist  Main_Rain
 105                0         0          0          0
 220                0         0          0          0
 341                0         0          0          0
 433                0         0          0          0
 545                0         0          0          0
 ...              ...       ...        ...        ...
 362928             0         0          0          1
 363041             0         0          0          1
 363159             0         0          0          1
 363274             0         0          0          1
 363389             0         0          0          1

 [3090 rows x 11 columns],
         number  available_bikes  Day  Hour   Temp  Main_Clear  Main_Clouds  \
 3           13                1    1     0   3.51           0            1
 119         13                0    1     0   3.51           0            1
 237         13                0    1     0   3.51           0            1
 366         13                0    1     0   3.51           0            1
 481         13                0    1     0   3.51           0            1
 ...        ...              ...  ...   ...    ...         ...          ...
 362896      13               12    7    23  10.39           0            0
 363009      13               12    7    23  10.39           0            0
 363124      13               12    7    23  10.39           0            0
 363240      13               11    7    23  10.39           0            0
 363357      13               11    7    23  10.39           0            0

         Main_Drizzle  Main_Fog  Main_Mist  Main_Rain
 3                  0         0          0          0
 119                0         0          0          0
 237                0         0          0          0
 366                0         0          0          0
 481                0         0          0          0
 ...              ...       ...        ...        ...
 362896             0         0          0          1
 363009             0         0          0          1
 363124             0         0          0          1
 363240             0         0          0          1
 363357             0         0          0          1

 [3088 rows x 11 columns],
 Empty DataFrame
 Columns: [number, available_bikes, Day, Hour, Temp, Main_Clear, Main_Clouds, Main_Drizzle, Main_Fog, Main_Mist, Main_Rain]
 Index: [],
         number  available_bikes  Day  Hour   Temp  Main_Clear  Main_Clouds  \
 45          15                3    1     0   3.51           0            1
 159         15                3    1     0   3.51           0            1
 273         15                3    1     0   3.51           0            1
 441         15                3    1     0   3.51           0            1
 553         15                4    1     0   3.51           0            1
 ...        ...              ...  ...   ...    ...         ...          ...
 362996      15                7    7    23  10.39           0            0
 363111      15                7    7    23  10.39           0            0

In [134]:
station_dfs[3][[col for col in station_dfs[0].columns if not (col == 'number')]].corr()

,available_bikes,Day,Hour,Temp,Main_Clear,Main_Clouds,Main_Drizzle,Main_Fog,Main_Mist,Main_Rain
available_bikes,1.000000,-0.119502,-0.093778,-0.328716,0.020928,-0.036316,-0.030361,0.134851,NaN,0.006854
Day,-0.119502,1.000000,0.003142,0.365411,0.003053,0.006755,0.148461,0.049283,NaN,-0.079944
Hour,-0.093778,0.003142,1.000000,0.357095,0.111229,-0.083210,0.056088,-0.082753,NaN,0.065172
Temp,-0.328716,0.365411,0.357095,1.000000,-0.129577,-0.036009,0.117542,-0.153359,NaN,0.075348
Main_Clear,0.020928,0.003053,0.111229,-0.129577,1.000000,-0.215999,-0.009286,-0.007052,NaN,-0.026358
Main_Clouds,-0.036316,0.006755,-0.083210,-0.036009,-0.215999,1.000000,-0.306473,-0.232760,NaN,-0.869934
Main_Drizzle,-0.030361,0.148461,0.056088,0.117542,-0.009286,-0.306473,1.000000,-0.010006,NaN,-0.037398
Main_Fog,0.134851,0.049283,-0.082753,-0.153359,-0.007052,-0.232760,-0.010006,1.000000,NaN,-0.028403
Main_Mist,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Main_Rain,0.006854,-0.079944,0.065172,0.075348,-0.026358,-0.869934,-0.037398,-0.028403,NaN,1.000000

In [135]:
station_dfs[0].dtypes

number               int64
available_bikes      int64
Day                  int64
Hour                 int64
Temp               float64
Main_Clear           uint8
Main_Clouds          uint8
Main_Drizzle         uint8
Main_Fog             uint8
Main_Mist            uint8
Main_Rain            uint8
dtype: object

In [136]:
linregs = [] 

features = [col for col in station_dfs[0].columns if not (col == 'number' or col == 'available_bikes')]
print(features)
for i in range(116):
    try:
        X = station_dfs[i][features]
        y = station_dfs[i].available_bikes
        linreg = LinearRegression().fit(X[features], y)
        linregs.append(linreg)
        filename = '/Users/lconroy/comp_msc/soft_eng/db_models/station_model_{0}.sav'.format(i + 2)
        pickle.dump(linreg, open(filename, 'wb'))
    except ValueError as ve:
        linregs.append(None)
        print(ve)

['Day', 'Hour', 'Temp', 'Main_Clear', 'Main_Clouds', 'Main_Drizzle', 'Main_Fog', 'Main_Mist', 'Main_Rain']
Found array with 0 sample(s) (shape=(0, 9)) while a minimum of 1 is required.
Found array with 0 sample(s) (shape=(0, 9)) while a minimum of 1 is required.
Found array with 0 sample(s) (shape=(0, 9)) while a minimum of 1 is required.
Found array with 0 sample(s) (shape=(0, 9)) while a minimum of 1 is required.
Found array with 0 sample(s) (shape=(0, 9)) while a minimum of 1 is required.
Found array with 0 sample(s) (shape=(0, 9)) while a minimum of 1 is required.

In [137]:
features = [col for col in station_dfs[0].columns if not (col == 'number')]

In [138]:
station_dfs[22][features].corr()

,available_bikes,Day,Hour,Temp,Main_Clear,Main_Clouds,Main_Drizzle,Main_Fog,Main_Mist,Main_Rain
available_bikes,1.000000,0.153446,0.252978,0.417272,0.004224,-0.098104,0.102606,-0.016025,NaN,0.074746
Day,0.153446,1.000000,0.004361,0.375874,0.003487,0.024287,0.138395,0.048472,NaN,-0.089815
Hour,0.252978,0.004361,1.000000,0.352392,0.102954,-0.085573,0.049418,-0.080187,NaN,0.073419
Temp,0.417272,0.375874,0.352392,1.000000,-0.121719,-0.027801,0.100974,-0.151513,NaN,0.066635
Main_Clear,0.004224,0.003487,0.102954,-0.121719,1.000000,-0.195580,-0.008210,-0.006417,NaN,-0.025639
Main_Clouds,-0.098104,0.024287,-0.085573,-0.027801,-0.195580,1.000000,-0.283982,-0.221946,NaN,-0.886846
Main_Drizzle,0.102606,0.138395,0.049418,0.100974,-0.008210,-0.283982,1.000000,-0.009317,NaN,-0.037228
Main_Fog,-0.016025,0.048472,-0.080187,-0.151513,-0.006417,-0.221946,-0.009317,1.000000,NaN,-0.029095
Main_Mist,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Main_Rain,0.074746,-0.089815,0.073419,0.066635,-0.025639,-0.886846,-0.037228,-0.029095,NaN,1.000000

In [139]:
X_new = pd.DataFrame({'Main_Clear': [0],
                      'Main_Clouds': [0],
                      'Main_Drizzle': [0],
                      'Main_Fog': [0],
                      'Main_Mist': 0,
                      'Main_Rain': [1],
                      'Day': [2], 'Hour': [12], 'Temp': [1.0]})
X_new.head()

,Main_Clear,Main_Clouds,Main_Drizzle,Main_Fog,Main_Mist,Main_Rain,Day,Hour,Temp
0,0,0,0,0,0,1,2,12,1.0

In [140]:
int(round(linregs[5].predict(X_new)[0]))

6

In [95]:
linreg_predictions = []
for i in range(116):
    try:
        linreg_predictions.append(linregs[i].predict(X_new))
    except AttributeError:
        print(None)

None
None
None
None
None
None

In [143]:
linreg_predictions

[array([2.55323213]),
 array([4.10713518]),
 array([12.09431938]),
 array([36.80314639]),
 array([10.33096165]),
 array([5.8921128]),
 array([6.3895291]),
 array([17.37573852]),
 array([14.73145622]),
 array([7.06186474]),
 array([0.403054]),
 array([7.42607758]),
 array([2.07847488]),
 array([3.09098411]),
 array([8.83520077]),
 array([21.89265905]),
 array([16.36973126]),
 array([15.47961522]),
 array([7.85095547]),
 array([9.15052881]),
 array([8.1680034]),
 array([3.8543318]),
 array([9.62319911]),
 array([12.39365828]),
 array([15.27532426]),
 array([12.72748806]),
 array([5.20715786]),
 array([2.28874691]),
 array([11.22280953]),
 array([3.93920595]),
 array([10.96566521]),
 array([20.856913]),
 array([12.21120023]),
 array([28.35394658]),
 array([8.22504867]),
 array([17.78888545]),
 array([6.75786276]),
 array([21.43389834]),
 array([4.4492607]),
 array([1.11807435]),
 array([22.28670359]),
 array([9.47440433]),
 array([13.96102436]),
 array([12.33654577]),
 array([10.34990254]),
 array([14.40054901]),
 array([17.10662203]),
 array([8.46197205]),
 array([12.08604607]),
 array([8.76245276]),
 array([6.57761441]),
 array([4.88704586]),
 array([11.54837214]),
 array([4.41762711]),
 array([15.01675472]),
 array([16.82047217]),
 array([5.85547551]),
 array([12.14071248]),
 array([7.76251571]),
 array([6.76266136]),
 array([21.32022935]),
 array([14.2646886]),
 array([28.21152471]),
 array([14.15417923]),
 array([7.1546468]),
 array([6.89511119]),
 array([6.74678171]),
 array([14.08736146]),
 array([10.4115575]),
 array([17.55331648]),
 array([27.34327264]),
 array([27.71766789]),
 array([11.664539]),
 array([9.56629473]),
 array([13.3937725]),
 array([15.72194811]),
 array([9.35649972]),
 array([10.60494875]),
 array([28.47535051]),
 array([17.48309875]),
 array([20.16231438]),
 array([7.72741864]),
 array([7.62803666]),
 array([14.03333709]),
 array([19.23861611]),
 array([26.40961917]),
 array([30.7019152]),
 array([7.96070449]),
 array([8.00786935]),
 array([14.42376257]),
 array([19.79452952]),
 array([6.49145672]),
 array([12.36823981]),
 array([12.72887343]),
 array([4.05441672]),
 array([1.86968041]),
 array([2.81319054]),
 array([6.31364828]),
 array([6.38751794]),
 array([6.43368392]),
 array([11.38277594]),
 array([11.59783186]),
 array([4.97849191]),
 array([17.4665044]),
 array([9.69826563]),
 array([3.82760506]),
 array([14.93545637]),
 array([19.50797251]),
 array([1.66993713]),
 array([12.32801077])]

In [144]:
loaded_model = pickle.load(open('/Users/lconroy/comp_msc/soft_eng/db_models/station_model_10.sav', 'rb'))

In [145]:
loaded_model

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [146]:
loaded_model.predict(X_new)

array([14.73145622])

In [148]:
X_new = pd.DataFrame({'Main_Clear': [1], 'Main_Clouds': [0], 'Main_Drizzle': [0], 'Main_Fog': [0], 'Main_Mist': [0], 'Main_Rain': [0], 'Day': [4], 'Hour': [23], 'Temp': [10]})
int(round(loaded_model.predict(X_new)[0]))

7

In [150]:
X_new['Main_Clear'] = [0]
X_new['Main_Clouds'] = [1]
X_new

,Main_Clear,Main_Clouds,Main_Drizzle,Main_Fog,Main_Mist,Main_Rain,Day,Hour,Temp
0,0,1,0,0,0,0,4,23,10

In [151]:
int(round(loaded_model.predict(X_new)[0]))

7